export const abonementSplideOptions = {
  perMove: 1,
  speed: 500,
  rewind: false,
  start: 0,
  // focus: 'center',
  // autoWidth: false,
  // autoHeight: true,
  // fixedHeight: '20rem',
  perPage: 5,
  gap: '1rem',
  // fixedWidth: '42rem',
  lazyLoad: 'nearby',
  pagination: false,
  arrows: false,
  drag: false,
  // focus: 'center',
  // keyboard: 'global',
  classes: {
    arrows: 'abonement__splider-controls',
    arrow: 'abonement__splider-arrow splider-arrow',
    prev: 'abonement__splider-arrow--prev splider-arrow--prev',
    next: 'abonement__splider-arrow--next splider-arrow--next',
    // pagination: 'abonement__splider-pagination splider-pagination',
  },
  breakpoints: {
    1200: {
      start: 1,
      arrows: true,
      // pagination: true,
      drag: true,
      perPage: 3,
    },
    1000: {
      // perPage: 3,
      // padding: '3rem',
    },
    620: {
      perPage: 2,
    },
    440: {
      start: 2,
      focus: 'center',
      // padding: '5rem',
      perPage: 1,
    },
  },
}
